### ISSUE TITLE
client list

### ISSUE THREAD

**Issue by nushahid** [lgothelipe/glpi_invoice#2]
hi,

i am trying to use invoice plugin for glpi 9.4. but it show me a list of entities instead of clients.
i think there is an error in code. please tell me if i'am missing something.

thanks in advance!

**Comment by lgothelipe** [comment]
Hi,

The plugin was designed to get the entities as clients.

The root entity could be your company and each entity a client.

**Comment by lgothelipe** [comment]
Hi,

The plugin was designed to get the entities as clients.

The root entity could be your company and each entity a client.
