### ISSUE TITLE
GLPI 9.5.x (10.x)

### ISSUE THREAD

**Issue by redfish8** [lgothelipe/glpi_invoice#3]
Hi,
Seems your plugin may respond to our requirements but as it's development looks stalled I ask if you plan to adapt to current and future GLPI releases ?

Thank you

Patrick

**Comment by FathiBenNasr** [comment]
What needs to be done to adapt it to 9.5.x ? I would like to use it.

**Comment by lgothelipe** [comment]
I haven't touch on this repo for a while. It probably needs to refactor most of the code.
Tbh don't know if I plan to do it.
